[tool.black]
extend-exclude = '^/typings/weechat.pyi'

[tool.poetry]
name = "wee-slack"
version = "3.0.0"
description = ""
license = "MIT"
authors = ["Trygve Aaberge <trygveaa@gmail.com>"]
readme = "README.md"
repository = "https://github.com/wee-slack/wee-slack"
# packages = [{include = "wee_slack"}]
# packages = [{ include = "." }]

[tool.poetry.dependencies]
python = "^3.7"
websocket-client = ">= 0.37.0"

[tool.poetry.group.dev.dependencies]
black = "^22.8.0"
pytest = "^7.1.3"
pytest-cov = "^4.0.0"

[tool.pylint.main]
ignored-modules = ["weechat"]

[tool.pylint."messages control"]
disable = [
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "no-member",
]

[tool.pyright]
strict = ["**"]
reportMissingModuleSource = false


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
