name: wee-slack
on: [push, pull_request]

jobs:
  test:
    if: >
      github.event_name == 'push' || (
        github.event_name == 'pull_request' &&
        github.event.pull_request.head.repo.full_name != github.repository
      )

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - run: pip install --upgrade pipenv
      - run: pipenv install --dev --skip-lock

      - name: Lint with Flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          pipenv run flake8 .

          # exit-zero treats all errors as warnings.
          pipenv run flake8 . --exit-zero --select=C,E,F,W

      - name: Check Python formatting
        run: |
          pipenv run black --check .

      - name: python/test
        run: |
          pipenv run pytest
